export let FooterData = [
    {
        link: "#",
        title: "Company",
        opt1: "About Us",
        opt2: "Our Philosophy",
        opt3: "Our Staff",
        opt4: "Our Faculity",
        opt5: "Careers",
        opt6: "Media Gallery",
    },
    {
        link: "#",
        title: "Admissions",
        opt1: "Admission Policy",
        opt2: "Getting Started",
        opt3: "Online Application",
        opt4: "Visa Information",
        opt5: "Tution Calculator",
        opt6: "Request Information",
    },
    {
        link: "#",
        title: "Students",
        opt1: "Student Life",
        opt2: "International Students",
        opt3: "Resources",
        opt4: "Form Download",
        opt5: "Testimonials",
        opt6: "",
    },
]